spring.application.name=homeflow
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_HomeFlow
spring.datasource.username=postgres
spring.datasource.password=admin

!llave con minimos 36 caracteres
jwt.secret=esta_es_una_clave_secreta_super_larga_para_mi_proyecto_react_vite_12345
logging.level.org.springframework.security=DEBUG


!spring.jpa.hibernate.ddl-auto=update <- Actualiza en automático la base de datos basado en las entidades