spring.datasource.url=jdbc:postgresql://localhost:5432/DB_HomeFlow
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

!llave con minimos 36 caracteres
jwt.secret=esta_es_una_clave_secreta_super_larga_para_mi_proyecto_react_vite_12345
logging.level.org.springframework.security=DEBUG

!Correo de verificacion
spring.mail.host = smtp.gmail.com
spring.mail.port=587
spring.mail.username=homeflowone@gmail.com
spring.mail.password=jsqtgguoldyskcdz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


!spring.jpa.hibernate.ddl-auto=update <- Actualiza en automático la base de datos basado en las entidades