spring.application.name=homeflow
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_HomeFlow
spring.datasource.username=postgres
spring.datasource.password=admin

!spring.jpa.hibernate.ddl-auto=update <- Actualiza en automático la base de datos basado en las entidades